name: Task CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

env:
  TEST_DB_URL: ${{ secrets.DB_URL }}
  TEST_DB_USERNAME: ${{ secrets.DB_USERNAME }}
  TEST_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build 
  
    - name: Finalize Build
      run: echo "Build completed successfully!"
